updateExtFibs <-
function(configdir='/Applications/Work/configure-7.10.Darwin'){
configdir=path.expand(configdir)
configdir=paste(configdir,'/',sep='')
check=try(download.file('ftp://site-ftp.aao.gov.au/pub/local/2df/latest_config_files/tdFconstantsDF.sds',destfile='temp'))
if(class(check)!='try-error'){file.rename(from='temp',to=paste(configdir,'tdFconstantsDF.sds',sep=''))}
#try(download.file('ftp://site-ftp.aao.gov.au/pub/local/2df/latest_config_files/2dF_distortion.map',destfile=paste(configdir,'2dF_distortion.map',sep='')))
#try(download.file('ftp://site-ftp.aao.gov.au/pub/local/2df/latest_config_files/tdFconstants400.sds',destfile=paste(configdir,'tdFconstants400.sds',sep='')))
check=try(download.file('ftp://site-ftp.aao.gov.au/pub/local/2df/latest_config_files/tdFconstants400.sds',destfile='temp'))
if(class(check)!='try-error'){file.rename(from='temp',to=paste(configdir,'tdFconstants400.sds',sep=''))}
#try(download.file('ftp://site-ftp.aao.gov.au/pub/local/2df/latest_config_files/tdFdistortion0.sds',destfile=paste(configdir,'tdFdistortion0.sds',sep='')))
check=try(download.file('ftp://site-ftp.aao.gov.au/pub/local/2df/latest_config_files/tdFdistortion0.sds',destfile='temp'))
if(class(check)!='try-error'){file.rename(from='temp',to=paste(configdir,'tdFdistortion0.sds',sep=''))}
#try(download.file('ftp://site-ftp.aao.gov.au/pub/local/2df/latest_config_files/tdFdistortion1.sds',destfile=paste(configdir,'tdFdistortion1.sds',sep='')))
check=try(download.file('ftp://site-ftp.aao.gov.au/pub/local/2df/latest_config_files/tdFdistortion1.sds',destfile='temp'))
if(class(check)!='try-error'){file.rename(from='temp',to=paste(configdir,'tdFdistortion1.sds',sep=''))}
#try(download.file('ftp://site-ftp.aao.gov.au/pub/local/2df/latest_config_files/tdFlinear0.sds',destfile=paste(configdir,'tdFlinear0.sds',sep='')))
check=try(download.file('ftp://site-ftp.aao.gov.au/pub/local/2df/latest_config_files/tdFlinear0.sds',destfile='temp'))
if(class(check)!='try-error'){file.rename(from='temp',to=paste(configdir,'tdFlinear0.sds',sep=''))}
#try(download.file('ftp://site-ftp.aao.gov.au/pub/local/2df/latest_config_files/tdFlinear1.sds',destfile=paste(configdir,'tdFlinear1.sds',sep='')))
check=try(download.file('ftp://site-ftp.aao.gov.au/pub/local/2df/latest_config_files/tdFlinear1.sds',destfile='temp'))
if(class(check)!='try-error'){file.rename(from='temp',to=paste(configdir,'tdFlinear1.sds',sep=''))}
closeAllConnections()}
